[package]
name    = "merkle"
version = "1.0.0"
authors = [
  "Frederic Jacobs <me@fredericjacobs.com>",
  "Dylan Bourgeois <dtsbourg@gmail.com>",
  "Romain Ruetschi <romain.ruetschi@gmail.com>"
]

description   = "Merkle is a Rust implementation of a Merkle tree with support for generation of inclusion proofs."
license       = "BSD-3-Clause"
documentation = "https://spinresearch.github.io/merkle.rs/merkle/index.html"
homepage      = "https://github.com/SpinResearch/merkle.rs"
repository    = "https://github.com/SpinResearch/merkle.rs"

[dependencies]
ring = "0.6.0-alpha"
protobuf = { version = "^1.0.0", optional = true }

[features]
serialization-protobuf = [ "protobuf" ]
